trigger:
- master
- '*'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'github.com,192.30.255.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaIIB9KC1ugvvXUEXVUHE2KblsA16g80AkYLDPkFAE8SNTBN8hlZj+2TFPCoxbjxaZiAtRuohbgsfKKioZOQRow9U4y/ytzSRPzxgPseFQWosCIo6zWCskH25tm9NoEK2m80zgjBDY7fCtnHV8MQVZdWc0Qitz8PMox3rBtAykZoTIlG5G7iF2L/BJJUe1hpXHhNDrh/JG3TAc6J6XmCSqUaUyu4PDaTDyrW9aStUt0bkyK6RDYxZBBb0ssEWOtmFWRxsXx+f5WrHR+B+UaINS503O2isSw6ItsfKtwjjBHcx7qO90nzlVML+PpPOZSdXI4D/ftTvrVKyPjF7TEwXj yvonneradsmikham@Yvonnes-MBP.guest.corp.microsoft.com
    #sshPassphrase: # Optional
    sshKeySecureFile: id_rsa

- bash: |
    curl $BEDROCK_BUILD_SCRIPT > build.sh
    chmod +x ./build.sh
    pwd
  displayName: Download Bedrock orchestration script
  env:
    BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/microsoft/bedrock/master/gitops/azure-devops/build.sh

- task: ShellScript@2
  displayName: Validate fabrikate definitions
  inputs:
    scriptPath: build.sh
  condition: eq(variables['Build.Reason'], 'PullRequest')
  env:
    VERIFY_ONLY: 1

- bash: |
    cp -r ./* "$HOME/"
    cd $HOME
    echo "-----------------------TESTING GIT CLONE VIA SSH-----------------------"
    #mkdir ydawgie
    #cd ydawgie
    #git clone git@github.com:bnookala/hello-rings.git
    #cd hello-rings
    #echo "LISTING CONTENT OF HELLO-RINGS REPO:"
    #ls -a
    #cd $HOME
    echo "-----------------------KNOWN HOSTS FILE-----------------------"
    cat .ssh/known_hosts
    echo "--------------------------RUN RAW BUILD.SH-----------------------------"
    wget "https://github.com/Microsoft/fabrikate/releases/download/0.15.0/fab-v0.15.0-linux-amd64.zip"
    unzip fab-v0.15.0-linux-amd64.zip -d fab
    export PATH=$PATH:$HOME/fab
    git clone https://github.com/bnookala/hello-rings-cluster-v2
    cd hello-rings-cluster-v2
    fab install
    cat .ssh/known_hosts
  displayName: Transform fabrikate definitions and publish to YAML manifests to repo
  condition: ne(variables['Build.Reason'], 'PullRequest')
  env:
    COMMIT_MESSAGE: $(Build.SourceVersionMessage)
    REPO: "https://github.com/bnookala/hello-rings-cluster-materialized"
    BRANCH_NAME: $(Build.SourceBranchName)
    VERSION: "0.12.0"