subcomponents:
  hello-rings-featurea:
    config:
      branchName: featurea
      buildDate: "2019-07-10T21:24:01.0345894Z"
      buildId: "4966"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurea-4966
  hello-rings-featureb:
    config:
      branchName: featureb
      buildDate: "2019-07-10T21:57:23.4163298Z"
      buildId: "4970"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featureb-4970
  hello-rings-featurec:
    config:
      branchName: featurec
      buildDate: "2019-08-07T21:30:07.3141419Z"
      buildId: "5641"
      commitId: 376326f02613aa0e7e826b4f1fbaa77cba62a003
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurec-5641
  hello-rings-featured:
    config:
      branchName: featured
      buildDate: "2019-08-07T21:03:02.3367674Z"
      buildId: "5635"
      commitId: b2b120461edcea3b22f63dc352c4f28e8436c6f1
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featured-5635
  hello-rings-featurey:
    config:
      branchName: featurey
      buildDate: "2019-08-07T22:13:18.5492919Z"
      buildId: "5651"
      commitId: 376326f02613aa0e7e826b4f1fbaa77cba62a003
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurey-5651
  hello-rings-featurez:
    config:
      branchName: featurez
      buildDate: "2019-07-10T18:12:16.1587898Z"
      buildId: "4949"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurez-4949
  hello-rings-master:
    config:
      branchName: master
      buildDate: "2019-10-17T06:02:29.5606539Z"
      buildId: "6527"
      commitId: 4cc3cc2093f7f602619bf09b2b87a0ab9ad77876
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-master-6527
