subcomponents:
  Build:
    subcomponents:
      BuildId:
        config:
          branchName: master
          buildDate: "2019-07-17T20:33:45.0897686Z"
          buildId: "5229"
          commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
          image:
            repository: hellorings.azurecr.io/hellorings
            tag: hello-rings-master-5229
  hello-rings-featurea:
    config:
      branchName: featurea
      buildDate: "2019-07-10T21:24:01.0345894Z"
      buildId: "4966"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurea-4966
  hello-rings-featureb:
    config:
      branchName: featureb
      buildDate: "2019-07-10T21:57:23.4163298Z"
      buildId: "4970"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featureb-4970
  hello-rings-featurec:
    config:
      branchName: featurec
      buildDate: "2019-07-11T16:14:36.1122165Z"
      buildId: "5012"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurec-5012
  hello-rings-featurez:
    config:
      branchName: featurez
      buildDate: "2019-07-10T18:12:16.1587898Z"
      buildId: "4949"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurez-4949
