subcomponents:
  hello-rings-featurez:
    config:
      branchName: featurez
      buildDate: "2019-07-10T18:12:16.1587898Z"
      buildId: "4949"
      commitId: 7c998ada452f1013e0a1f08acab81a6d35e730b2
      image:
        repository: hellorings.azurecr.io/hellorings
        tag: hello-rings-featurez-4949
